/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.npptmk.bazaTest.defect;

import java.awt.Frame;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import ru.npptmk.bazaTest.defect.model.Customer;

/**
 *
 * @author RazumnovAA
 */
public class DialogCustomerCreation extends javax.swing.JDialog {

    private EntityManagerFactory emf;

    /**
     * Creates new form DialogCustomerCreation
     */
    public DialogCustomerCreation(Frame parent, boolean modal, EntityManagerFactory emf) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.emf = emf;
    }

    public void setEntityManager(EntityManagerFactory emf) {
        this.emf = emf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lablel_CustomerName = new javax.swing.JLabel();
        field_CustomerName = new javax.swing.JTextField();
        button_SaveCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Создание нового заказчика");
        setMaximumSize(new java.awt.Dimension(400, 88));
        setMinimumSize(new java.awt.Dimension(400, 88));
        setResizable(false);

        lablel_CustomerName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lablel_CustomerName.setText("Название заказчика");

        field_CustomerName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        button_SaveCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_SaveCustomer.setText("Сохранить и закрыть");
        button_SaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_SaveCustomer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lablel_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lablel_CustomerName)
                    .addComponent(field_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_SaveCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_SaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveCustomerActionPerformed
        //
        if (!field_CustomerName.getText().equals("")) {
            EntityManager em = emf.createEntityManager();
            try {
                EntityTransaction trans = em.getTransaction();
                try {
                    trans.begin();
                    Customer customer = new Customer();
                    customer.setName(field_CustomerName.getText());
                    em.persist(customer);
                    trans.commit();
                    JOptionPane.showMessageDialog(
                            null,
                            "Новый заказчик успешно сохранен.",
                            "Уведомленеие",
                            INFORMATION_MESSAGE
                    );
                } finally {
                    if (trans.isActive()) {
                        trans.rollback();
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(
                        null,
                        "Не удалось сохранить нового заказчика.",
                        "Ошибка",
                        ERROR_MESSAGE
                );
            } finally {
                if (em != null) {
                    em.close();
                }
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Поле с именем заказчика не может быть пустым.",
                    "Предупреждение",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_button_SaveCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_SaveCustomer;
    private javax.swing.JTextField field_CustomerName;
    private javax.swing.JLabel lablel_CustomerName;
    // End of variables declaration//GEN-END:variables
}
