/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.npptmk.bazaTest.defect;

import java.lang.reflect.Field;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ru.npptmk.devices.USKUdp.DeltaGainPanel;
import ru.npptmk.guiObjects.AbstractVKEditor;
import ru.npptmk.guiObjects.VirtualKeyboard;

/**
 * Диалог основных параметрв линии дефектоскопии.
 *
 * @author MalginAS
 */
public class MainParametersDialog extends javax.swing.JDialog {

    public boolean isChanged = false;
    private Field[] fields = this.getClass().getFields();
    private final VirtualKeyboard vk = new VirtualKeyboard(null);

    /**
     * Добавлено создание с панелью ослабления усилений каналов по типам
     *
     * @param par
     * @param ltt
     * @param tt
     * @param pn панель ослабления усилений каналов.
     */
    public MainParametersDialog(UEParams par, DeltaGainPanel pn) {
        this(par, par.tubeTypes, par.currentTubeType);
        jPanel1.add(pn);
        pack();
    }

    /**
     * Creates new form MainParametersDialog
     *
     * @param par Параметры линии.
     * @param ltt Список типов труб в системе.
     * @param tt Идентификатор текущего типа трубы.
     */
    public MainParametersDialog(UEParams par, List<TubeType> ltt, TubeType tt) {
        super((java.awt.Frame) null, true);
        initComponents();
        edCalibrLength.setText(String.valueOf(par.calibrLen));
        edMDEnd.setText(String.valueOf(par.MDEnd));
        edMDStart.setText(String.valueOf(par.MDStart));
        edSecLirStart.setText(String.valueOf(par.secLirStart));
        edTailLen.setText(String.valueOf(par.tailLen));
        edThirdLirStart.setText(String.valueOf(par.thdLirStart));
        edUSDEnd.setText(String.valueOf(par.USDEnd));
        edUSDStart.setText(String.valueOf(par.USDStart));
        edTime.setText(String.valueOf(par.fillTime));
        edIntSave.setText(String.valueOf(par.intSave));
        edOnWatter.setText(String.valueOf(par.onWatter));
        edOffWater.setText(String.valueOf(par.offWatter));
        edOnDry.setText(String.valueOf(par.onDry));
        edOffDry.setText(String.valueOf(par.offDry));
        for (TubeType ctt : ltt) {
            cbTubeTypes.addItem(ctt);
            if (ctt.equals(tt)) {
                cbTubeTypes.setSelectedItem(ctt);
            }
        }
        //Устанавливаем панели цифрового ввода для всех JTextField
        try {
            for (Field field : fields) {
                //Если поле класса JTextFiled
                if (field.getType().equals(JTextField.class)) {
                    new AbstractVKEditor((JTextField) field.get(this), vk) {
                        @Override
                        public void newValue(String newVal) {
                            edCalibrLength.setText(newVal);
                        }
                    };
                }
            }
        } catch (IllegalAccessException | IllegalArgumentException e) {
            Logger.getGlobal().log(Level.SEVERE, "Не возможно установить панельки цифрового ввода.");
        }

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTubeTypes = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        button_SaveAndClose = new javax.swing.JButton();
        button_Close = new javax.swing.JButton();
        edCalibrLength = new javax.swing.JTextField();
        edMDStart = new javax.swing.JTextField();
        edUSDStart = new javax.swing.JTextField();
        edSecLirStart = new javax.swing.JTextField();
        edThirdLirStart = new javax.swing.JTextField();
        edTailLen = new javax.swing.JTextField();
        edMDEnd = new javax.swing.JTextField();
        edUSDEnd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edTime = new javax.swing.JTextField();
        edIntSave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        edOffWater = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edOnWatter = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edOffDry = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        edOnDry = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Параметры линии дефектоскопии.");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Тип трубы");

        cbTubeTypes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Длина калибровочного участка мм.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Координата начала магнитной дефектоскопии мм.");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Координата начала УЗД мм.");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Координата опускания второго прижима мм.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Координата опускания третьего прижима мм.");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Координата подъема первого прижима мм.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Координата окончания магнитной дефектоскопии мм.");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Координата окончания УЗД мм.");

        button_SaveAndClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_SaveAndClose.setText("Сохранить и закрыть");
        button_SaveAndClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveAndCloseActionPerformed(evt);
            }
        });

        button_Close.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_Close.setText("Закрыть");
        button_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CloseActionPerformed(evt);
            }
        });

        edCalibrLength.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edCalibrLength.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edCalibrLength.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edMDStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edMDStart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edMDStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edUSDStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edUSDStart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edUSDStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edSecLirStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edSecLirStart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edSecLirStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edThirdLirStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edThirdLirStart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edThirdLirStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edTailLen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edTailLen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edTailLen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edMDEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edMDEnd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edMDEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edUSDEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edUSDEnd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edUSDEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Время заполнения каретки водой сек.");

        edTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        edIntSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edIntSave.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edIntSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Шаг х-координаты графиков, мм.");

        jPanel1.setLayout(new java.awt.BorderLayout());

        edOffWater.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edOffWater.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edOffWater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Координата окончания смачивания, мм.");

        edOnWatter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edOnWatter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edOnWatter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Координата начала смачивания, мм.");

        edOffDry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edOffDry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edOffDry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Координата окончания осушки, мм.");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Координата начала осушки, мм.");

        edOnDry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edOnDry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edOnDry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edMDStartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(edTime))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edUSDStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edUSDEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edOffWater, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(edMDStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(edMDEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(41, 41, 41)
                                            .addComponent(cbTubeTypes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(edOnWatter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(button_SaveAndClose)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(button_Close)))
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edSecLirStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edIntSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edCalibrLength, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edTailLen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edThirdLirStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edOnDry, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edOffDry, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {edCalibrLength, edMDEnd, edMDStart, edSecLirStart, edTailLen, edThirdLirStart, edTime, edUSDEnd, edUSDStart});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTubeTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(edTailLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(edMDStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(edMDEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(edUSDStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(edUSDEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(edOnWatter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edSecLirStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edThirdLirStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(edIntSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edCalibrLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(edOnDry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(edOffDry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edOffWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(edTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_SaveAndClose)
                    .addComponent(button_Close))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {edCalibrLength, edMDEnd, edSecLirStart, edTailLen, edThirdLirStart, edTime, edUSDEnd, edUSDStart});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_SaveAndCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveAndCloseActionPerformed
        isChanged = true;
        setVisible(false);
    }//GEN-LAST:event_button_SaveAndCloseActionPerformed

    private void button_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CloseActionPerformed
        isChanged = false;
        setVisible(false);
    }//GEN-LAST:event_button_CloseActionPerformed

    private void edMDStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edMDStartMouseClicked
        VirtualKeyboard vk = new VirtualKeyboard(null);
        String newVal = vk.getValue(
                evt.getComponent(),
                ((JTextField) evt.getSource()).getText());
        if (newVal != null) {
            ((JTextField) evt.getSource()).setText(newVal);
        }
    }//GEN-LAST:event_edMDStartMouseClicked
    /**
     * Обновляет параметры в соответствии с введенными в поля панели.
     *
     * @param prm парметры которые небходимо обоновить с панели.
     */
    public void updateParams(UEParams prm) {
        try {
            prm.calibrLen = Short.valueOf(edCalibrLength.getText());
            prm.MDEnd = Short.valueOf(edMDEnd.getText());
            prm.MDStart = Short.valueOf(edMDStart.getText());
            prm.secLirStart = Short.valueOf(edSecLirStart.getText());
            prm.tailLen = Short.valueOf(edTailLen.getText());
            prm.thdLirStart = Short.valueOf(edThirdLirStart.getText());
            prm.USDEnd = Short.valueOf(edUSDEnd.getText());
            prm.USDStart = Short.valueOf(edUSDStart.getText());
            prm.fillTime = Short.valueOf(edTime.getText());
            prm.intSave = Short.valueOf(edIntSave.getText());
            prm.onWatter = Short.valueOf(edOnWatter.getText());
            prm.offWatter = Short.valueOf(edOffWater.getText());
            prm.onDry = Short.valueOf(edOnDry.getText());
            prm.offDry = Short.valueOf(edOffDry.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Данные введены неверно");
        }
    }

    /**
     * Возвращает установленный пользователем тип трубы.
     *
     * @return Тип трубы.
     */
    public TubeType getTubeType() {
        return (TubeType) cbTubeTypes.getSelectedItem();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Close;
    private javax.swing.JButton button_SaveAndClose;
    private javax.swing.JComboBox cbTubeTypes;
    private javax.swing.JTextField edCalibrLength;
    private javax.swing.JTextField edIntSave;
    private javax.swing.JTextField edMDEnd;
    private javax.swing.JTextField edMDStart;
    private javax.swing.JTextField edOffDry;
    private javax.swing.JTextField edOffWater;
    private javax.swing.JTextField edOnDry;
    private javax.swing.JTextField edOnWatter;
    private javax.swing.JTextField edSecLirStart;
    private javax.swing.JTextField edTailLen;
    private javax.swing.JTextField edThirdLirStart;
    private javax.swing.JTextField edTime;
    private javax.swing.JTextField edUSDEnd;
    private javax.swing.JTextField edUSDStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
