/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.npptmk.bazaTest.defect;

import java.awt.Frame;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.TableModel;

/**
 *
 * @author RazumnovAA
 */
public class TubeTypesDialog extends javax.swing.JDialog {

    private boolean saveChanges;
    
    private EntityManager em;

    /**
     * Creates new form TubeTypesDialog
     * @param parent
     * @param modal если true, то данное окно блокирует остальной интерфейс.
     */
    public TubeTypesDialog(Frame parent, boolean modal) {
        super(parent, modal);
        customInitComponents(null);
    }

    public TubeTypesDialog(
            Frame parent,
            boolean modal,
            TubeTypesTableModel tubeTypesTableModel) {
        super(parent, modal);
        customInitComponents(tubeTypesTableModel);
        
    }
    
    /**
     * Получает список типов труб из таблицы.
     * 
     * @return существующий списко типовт труб.
     */
    public List<TubeType> getTubeTypesList(){
        return ((TubeTypesTableModel) jTable1.getModel()).getTubeTypesList();
    }

    public final void customInitComponents(TableModel tableModel){
        initComponents();
        if (tableModel == null){
            jTable1.setModel(new TubeTypesTableModel());
        }else{
            jTable1.setModel(tableModel);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_RemoveSelected = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button_AddNewType = new javax.swing.JButton();
        button_Save = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 435));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", 0, 18));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        button_RemoveSelected.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button_RemoveSelected.setText("Удалить выделенные типы");
        button_RemoveSelected.setEnabled(false);
        button_RemoveSelected.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_RemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RemoveSelectedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Список типов труб");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        button_AddNewType.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button_AddNewType.setText("Добавить новый тип");
        button_AddNewType.setPreferredSize(new java.awt.Dimension(153, 25));
        button_AddNewType.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_AddNewType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddNewTypeActionPerformed(evt);
            }
        });

        button_Save.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button_Save.setText("Сохранить в базу");
        button_Save.setPreferredSize(new java.awt.Dimension(135, 25));
        button_Save.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_RemoveSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_AddNewType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_RemoveSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_AddNewType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_RemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RemoveSelectedActionPerformed
        int minSelectionIndex = jTable1.getSelectionModel().getMinSelectionIndex();
        int maxSelectionIndex = jTable1.getSelectionModel().getMaxSelectionIndex();
        if (maxSelectionIndex != -1 && minSelectionIndex != -1){
            if (maxSelectionIndex == minSelectionIndex){
            //Удаляем выделенную строку
            ((TubeTypesTableModel)jTable1.getModel()).removeRow(maxSelectionIndex);
        }else{
              //Удаляем выделенные строки
              ((TubeTypesTableModel)jTable1.getModel()).removeRow(
                      minSelectionIndex,
                      maxSelectionIndex);
            }
        }
    }//GEN-LAST:event_button_RemoveSelectedActionPerformed

    private void button_AddNewTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddNewTypeActionPerformed
        //Добавляем новую строку для создания типа трубы
        ((TubeTypesTableModel)jTable1.getModel()).addRow();
    }//GEN-LAST:event_button_AddNewTypeActionPerformed

    private void button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveActionPerformed
        this.saveChanges = true;
    }//GEN-LAST:event_button_SaveActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        saveChanges = false;
    }//GEN-LAST:event_formComponentHidden

     public void setVisible(List<TubeType> tubeTypes, boolean isVisible){
         ((TubeTypesTableModel)jTable1.getModel()).cloneContainer(tubeTypes);
         super.setVisible(isVisible);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_AddNewType;
    private javax.swing.JButton button_RemoveSelected;
    private javax.swing.JButton button_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * Сообщает влядельцу диалога что внесенные изменения должны быть
     * сохранены в базу данных.
     * 
     * @return true - сохранить изменения. false - не сохранять изменения.
     */
    boolean ShouldSaveChanges() {
        return saveChanges;
    }
}
