package ru.npptmk.baza_test.defect.util;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author RazumnovAA
 * @param <T> Тип представляющий собой результат возвращаемый диалогом.
 */
public class ProgressDialog extends javax.swing.JDialog implements PropertyChangeListener {

    /**
     * Creates new form ProgressDialog
     */
    public ProgressDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.setTitle("УНКТ-500");

    }
    private Object result;
    public <T> T getResult() {
        return (T) result;
    }
    public <T> void setResult(T result) {
        this.result = result;
    }
    private SwingWorker processToMonitor;

    private String processName;

    public void startProcessing(
            String processName,
            Integer endValue,
            SwingWorker<Integer, Integer> processToMonitor) {
        this.setLocationRelativeTo(null);
        this.progressBar.setIndeterminate(false);
        this.processToMonitor = processToMonitor;
        this.processToMonitor.execute();
        this.processName = processName;
        this.progressBar.setMaximum(endValue);
        this.processNameLabel.setText(processName);
        this.progressBar.setValue(0);
        this.setVisible(true);

    }

    public void startProcessing(
            String processName,
            SwingWorker<Integer, Integer> processToMonitor) {
        this.setLocationRelativeTo(null);
        this.progressBar.setIndeterminate(true);
        this.processToMonitor = processToMonitor;
        this.processToMonitor.execute();
        this.processName = processName;
        this.processNameLabel.setText(this.processName);
        this.setVisible(true);
    }

    public synchronized void increment() {
        SwingUtilities
                .invokeLater(() -> this.progressBar
                        .setValue(this.progressBar.getValue() + 1));
        ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        processNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        processNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(processNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel processNameLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getNewValue() == "") {
            this.setVisible(false);
        }
    }
}
