/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.npptmk.devices.USKUdp;

import javax.swing.JOptionPane;
import ru.npptmk.guiObjects.AbstractVKEditor;
import ru.npptmk.guiObjects.VirtualKeyboard;

/**
 * Панель предназначена для задания изменения ослабления
 * усиления разных типов каналов: продольников, поперечников, толщинометрии.
 * @author SmorkalovAV
 */
public class DeltaGainPanel extends javax.swing.JPanel {

    private final DeviceUSKUdpParamPanel pnl;

    /**
     * Creates new form DeltaGainPanel
     */
    public DeltaGainPanel(DeviceUSKUdpParamPanel pn) {
        initComponents();
        pnl = pn;
        VirtualKeyboard vk = new VirtualKeyboard(null);
        new AbstractVKEditor(edAux, vk) {
            @Override
            public void newValue(String newVal) {
                float vl = 0;
                try{
                    vl = Float.valueOf(newVal.replace(",", "."));
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Значение введено неверно" + newVal);
                }
                if(vl >= 0){
                    edAux.setText(newVal);
                    pnl.deltaGainAxial = vl;
                    pnl.refreshFailAx();
                }
            }
        };
        new AbstractVKEditor(edValueDir, vk) {
            @Override
            public void newValue(String newVal) {
                float vl = 0;
                try{
                    vl = Float.valueOf(newVal.replace(",", "."));
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Значение ввдено неверно" + newVal);
                }
                if(vl >= 0){
                    edValueDir.setText(newVal);
                    pnl.deltaGainDir = vl;
                    pnl.refreshFailDir();
                }
            }
        };
        new AbstractVKEditor(edValueTol, vk) {
            @Override
            public void newValue(String newVal) {
                float vl = 0;
                try{
                    vl = Float.valueOf(newVal.replace(",", "."));
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Значение введено неверно." + newVal);
                }
                if(vl >= 0){
                    edValueTol.setText(newVal);
                    pnl.deltaGainThick = vl;
                    pnl.refreshFailTolsh();
                }
            }
        };
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edAux = new javax.swing.JTextField();
        btUpAux = new javax.swing.JButton();
        btDwnAux = new javax.swing.JButton();
        mess = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mess1 = new javax.swing.JLabel();
        btUpDir = new javax.swing.JButton();
        edValueDir = new javax.swing.JTextField();
        btDwnDir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        mess2 = new javax.swing.JLabel();
        btUpTol = new javax.swing.JButton();
        edValueTol = new javax.swing.JTextField();
        btDwnTol = new javax.swing.JButton();

        edAux.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        edAux.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edAux.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        edAux.setMinimumSize(new java.awt.Dimension(4, 32));
        edAux.setPreferredSize(new java.awt.Dimension(4, 32));

        btUpAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/051-add.png"))); // NOI18N
        btUpAux.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btUpAux.setMaximumSize(new java.awt.Dimension(32, 32));
        btUpAux.setMinimumSize(new java.awt.Dimension(32, 32));
        btUpAux.setName("200"); // NOI18N
        btUpAux.setPreferredSize(new java.awt.Dimension(32, 32));
        btUpAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpAuxActionPerformed(evt);
            }
        });

        btDwnAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/038-delete.png"))); // NOI18N
        btDwnAux.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btDwnAux.setMaximumSize(new java.awt.Dimension(32, 32));
        btDwnAux.setMinimumSize(new java.awt.Dimension(32, 32));
        btDwnAux.setName("201"); // NOI18N
        btDwnAux.setPreferredSize(new java.awt.Dimension(32, 32));
        btDwnAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDwnAuxActionPerformed(evt);
            }
        });

        mess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mess.setText("Ослабление продольных, дБ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mess, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btUpAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edAux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDwnAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(mess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btUpAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDwnAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mess1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mess1.setText("Ослабление поперечных, дБ");

        btUpDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/051-add.png"))); // NOI18N
        btUpDir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btUpDir.setMaximumSize(new java.awt.Dimension(32, 32));
        btUpDir.setMinimumSize(new java.awt.Dimension(32, 32));
        btUpDir.setName("200"); // NOI18N
        btUpDir.setPreferredSize(new java.awt.Dimension(32, 32));
        btUpDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpDirActionPerformed(evt);
            }
        });

        edValueDir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        edValueDir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edValueDir.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        edValueDir.setMinimumSize(new java.awt.Dimension(4, 32));
        edValueDir.setPreferredSize(new java.awt.Dimension(4, 32));

        btDwnDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/038-delete.png"))); // NOI18N
        btDwnDir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btDwnDir.setMaximumSize(new java.awt.Dimension(32, 32));
        btDwnDir.setMinimumSize(new java.awt.Dimension(32, 32));
        btDwnDir.setName("201"); // NOI18N
        btDwnDir.setPreferredSize(new java.awt.Dimension(32, 32));
        btDwnDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDwnDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mess1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btUpDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edValueDir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDwnDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(mess1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btUpDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edValueDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDwnDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mess2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mess2.setText("Ослабление толщинометрии, дБ");

        btUpTol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/051-add.png"))); // NOI18N
        btUpTol.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btUpTol.setMaximumSize(new java.awt.Dimension(32, 32));
        btUpTol.setMinimumSize(new java.awt.Dimension(32, 32));
        btUpTol.setName("200"); // NOI18N
        btUpTol.setPreferredSize(new java.awt.Dimension(32, 32));
        btUpTol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpTolActionPerformed(evt);
            }
        });

        edValueTol.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        edValueTol.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edValueTol.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        edValueTol.setMinimumSize(new java.awt.Dimension(4, 32));
        edValueTol.setPreferredSize(new java.awt.Dimension(4, 32));

        btDwnTol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/038-delete.png"))); // NOI18N
        btDwnTol.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btDwnTol.setMaximumSize(new java.awt.Dimension(32, 32));
        btDwnTol.setMinimumSize(new java.awt.Dimension(32, 32));
        btDwnTol.setName("201"); // NOI18N
        btDwnTol.setPreferredSize(new java.awt.Dimension(32, 32));
        btDwnTol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDwnTolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mess2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btUpTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edValueTol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDwnTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(mess2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btUpTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edValueTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDwnTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setEdAux(String edAux) {
        this.edAux.setText(edAux);
    }

    public void setEdValueDir(String edValueDir) {
        this.edValueDir.setText(edValueDir);
    }

    public void setEdValueTol(String edValueTol) {
        this.edValueTol.setText(edValueTol);
    }

    private void btUpAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpAuxActionPerformed
        pnl.upDeltaGainAx();
        setEdAux(String.format("%.1f", pnl.deltaGainAxial).replace('.', ','));
    }//GEN-LAST:event_btUpAuxActionPerformed

    private void btDwnAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDwnAuxActionPerformed
        pnl.dwnDeltaGainAx();
        setEdAux(String.format("%.1f", pnl.deltaGainAxial).replace('.', ','));
    }//GEN-LAST:event_btDwnAuxActionPerformed

    private void btUpDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpDirActionPerformed
        pnl.upDeltaGainDir();
        setEdValueDir(String.format("%.1f", pnl.deltaGainDir).replace('.', ','));
    }//GEN-LAST:event_btUpDirActionPerformed

    private void btDwnDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDwnDirActionPerformed
        pnl.dwnDeltaGainDir();
        setEdValueDir(String.format("%.1f", pnl.deltaGainDir).replace('.', ','));
    }//GEN-LAST:event_btDwnDirActionPerformed

    private void btDwnTolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDwnTolActionPerformed
        pnl.dwnDeltaGainThick();
        setEdValueTol(String.format("%.1f", pnl.deltaGainThick).replace('.', ','));
    }//GEN-LAST:event_btDwnTolActionPerformed

    private void btUpTolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpTolActionPerformed
        pnl.upDeltaGainThick();
        setEdValueTol(String.format("%.1f", pnl.deltaGainThick).replace('.', ','));
    }//GEN-LAST:event_btUpTolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDwnAux;
    private javax.swing.JButton btDwnDir;
    private javax.swing.JButton btDwnTol;
    private javax.swing.JButton btUpAux;
    private javax.swing.JButton btUpDir;
    private javax.swing.JButton btUpTol;
    private javax.swing.JTextField edAux;
    private javax.swing.JTextField edValueDir;
    private javax.swing.JTextField edValueTol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mess;
    private javax.swing.JLabel mess1;
    private javax.swing.JLabel mess2;
    // End of variables declaration//GEN-END:variables

    void refresh() {
        if(pnl != null){
            setEdAux(String.format("%.1f", pnl.deltaGainAxial).replace('.', ','));
            setEdValueDir(String.format("%.1f", pnl.deltaGainDir).replace('.', ','));
            setEdValueTol(String.format("%.1f", pnl.deltaGainThick).replace('.', ','));
        }
    }
}
